//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace Poc.Entity
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pocEntities : DbContext
    {
        static pocEntities()
    	{ 
    		Database.SetInitializer<pocEntities>(null);
    	}
    	
    	public pocEntities() : base("name=pocEntities")
        {
        }
    	
    	public pocEntities(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public pocEntities(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public pocEntities(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public pocEntities(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
    		modelBuilder.Conventions.Remove<IncludeMetadataConvention>();
    		modelBuilder.Configurations.Add(new Clientes_Mapping());
    		modelBuilder.Configurations.Add(new FormasPagamento_Mapping());
    		modelBuilder.Configurations.Add(new Grupos_Mapping());
    		modelBuilder.Configurations.Add(new ItensPedido_Mapping());
    		modelBuilder.Configurations.Add(new Pedidos_Mapping());
    		modelBuilder.Configurations.Add(new Produtos_Mapping());
    		modelBuilder.Configurations.Add(new Usuarios_Mapping());
        }
    	
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<FormasPagamento> FormasPagamento { get; set; }
        public DbSet<Grupos> Grupos { get; set; }
        public DbSet<ItensPedido> ItensPedido { get; set; }
        public DbSet<Pedidos> Pedidos { get; set; }
        public DbSet<Produtos> Produtos { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
