//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poc.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public Pedidos()
        {
            this.ItensPedido = new HashSet<ItensPedido>();
        }
    
        public long Id { get; set; }
        public System.DateTime DataPedido { get; set; }
        public long FormaPagamentoId { get; set; }
        public long ClienteId { get; set; }
        public decimal ValorTotal { get; set; }
        public long Numero { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> UltimaAtualizacao { get; set; }
        public long CriadoPor { get; set; }
        public Nullable<long> AtualizadoPor { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual FormasPagamento FormasPagamento { get; set; }
        public virtual ICollection<ItensPedido> ItensPedido { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
